apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml

configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml

namespace: longhorn-system

generatorOptions:
  disableNameSuffixHash: true