---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: blackbox-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 11.7.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: blackbox-exporter
  interval: 1h
  values:
    fullnameOverride: blackbox-exporter
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4
    serviceMonitor:
      enabled: true
      selfMonitor:
        enabled: true
    prometheusRule:
      enabled: true
      rules:
        - alert: ProbeFailed
          expr: |-
            probe_success{service="blackbox-exporter"} == 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The probe targeting {{ $labels.instance }} is currently having connectivity issues