---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: notifiarr
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notifiarr
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: notifiarr
    namespace: flux-system
  interval: 1h
  targetNamespace: media
  values:
    controllers:
      notifiarr:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            ports:
            - containerPort: &port 5454
              name: http
              protocol: TCP
            image:
              repository: golift/notifiarr
              tag: 0.9.2
            env:
              DN_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: notifiarr-secret
                    key: dn_api_key
              DN_RADARR_0_NAME: "Radarr-canadium"
              DN_RADARR_0_URL: "http://radarr:7878"
              DN_RADARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: api_key
              TZ: America/New_York
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                memory: 50Mi
              limits:
                memory: 50Mi
    service:
      app:
        ports:
          http:
            port: *port
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: "ReadWriteOnce"
        storageClass: longhorn
        size: 20Mi
    route:
      app:
        hostnames:
          - notifiarr.internal.beerus.fr
        parentRefs:
          - name: cilium-internal
            namespace: network