---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: signoz
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.signoz.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-release
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: kube-system
      interval: 12h
  install:
    createNamespace: true
  values:
    global:
      storageClass: longhorn
    clickhouse:
      installCustomStorageClass: true