---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: signoz
  namespace: platform
spec:
  interval: 24h
  url: https://charts.signoz.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-release
  namespace: platform
spec:
  interval: 30m
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: platform
      interval: 12h
  install:
    createNamespace: true
  values:
    global:
      storageClass: longhorn
    clickhouse:
      installCustomStorageClass: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-k8s-infra-release
  namespace: platform
spec:
  interval: 30m
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: k8s-infra
        namespace: platform
      interval: 12h