apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  path: "./00-core/06_cert-manager/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 5m
  timeout: 5m
  dependsOn:
    - name: cert-manager-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  path: "./00-core/06_cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 5m
  timeout: 5m
  dependsOn:
    - name: gatewayapi-release
  decryption:
    provider: sops
    secretRef:
      name: sops-age