apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "exposed-pool"
  namespace: kube-system
spec:
  blocks:
  - cidr: "192.168.68.128/29"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: web-gw
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: web-gw-secure
    port: 443
    protocol: HTTPS