apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatus-prereq
  namespace: flux-system
spec:
  path: "./10-platform/monitoring/gatus/prereq"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 5m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatus-releasee
  namespace: flux-system
spec:
  path: "./10-platform/monitoring/gatus/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 5m
  timeout: 15m
  dependsOn:
    - name: gatus-prereq