---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno-repo
  namespace: kyverno
spec:
  interval: 24h
  url: https://charts.kyverno.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-release
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      # version: "1.9.x"
      sourceRef:
        kind: HelmRepository
        name: kyverno-repo
        namespace: kyverno
      interval: 12h