apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  releaseName: external-secrets
  targetNamespace: external-secrets
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-secrets
      version: 0.9.19 # example version — pin to the one you want
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
