---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: platform
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry-release
  namespace: platform
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: platform
      interval: 12h
  values:
    admissionWebhooks:
      certManager:
        enabled: false
      autoGenerateCert:
        enabled: true
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s
      featureGates: "AutoinstrumentationGo=true"