---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: flux-system
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry-release
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    admissionWebhooks:
      certManager:
        enabled: false
      autoGenerateCert:
        enabled: true
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s
      extraArgs:
        - --enable-go-instrumentation=true