apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: x3gallery-release
  namespace: flux-system
spec:
  path: "./20-apps/default/x3gallery/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: x3gallery-config
  namespace: flux-system
spec:
  path: "./10-platform/network/x3gallery/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: x3gallery-release