---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  interval: 1h
  targetNamespace: cloud
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v2.5.5
            env:
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              # Add the env vars to connect to your database here.

    immich:
      metrics:
        enabled: true
      persistence:
        # Main data store for all photos shared between different components.
        library:
          # Automatically creating the library volume is not supported by this chart
          # You have to specify an existing PVC to use
          existingClaim: immich-pvc
      # configuration is immich-config.json converted to yaml
      # ref: https://immich.app/docs/install/config-file/
      #
      configuration: {}
        # trash:
        #   enabled: false
        #   days: 30
        # storageTemplate:
        #   enabled: true
        #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
      # Sets the resource Kind to store configuration in. Must be either ConfigMap or Secret.
      configurationKind: ConfigMap

    # Dependencies
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: docker.io/valkey/valkey
                tag: 9.0-alpine3.23
                pullPolicy: IfNotPresent
      persistence:
        data:
          enabled: true
          size: 1Gi
          type: emptyDir
          accessMode: ReadWriteOnce

    # Immich components
    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                pullPolicy: IfNotPresent

    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                pullPolicy: IfNotPresent
              env:
                TRANSFORMERS_CACHE: /cache
                HF_XET_CACHE: /cache/huggingface-xet
                MPLCONFIGDIR: /cache/matplotlib-config
      persistence:
        cache:
          enabled: true
          size: 10Gi
          # Optional: Set this to persistentVolumeClaim to avoid downloading the ML models every start.
          type: emptyDir
          accessMode: ReadWriteMany
          # storageClass: your-class
    route:
      server:
        hostnames:
          - immich.beerus.fr
        parentRefs:
          - name: cilium-external
            namespace: network
            sectionName: https