---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubereboot.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubereboot-release
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kured
      version: "5.x.x"
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: kube-system
      interval: 12h