apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-release
  namespace: flux-system
spec:
  path: "./00-core/01_cilium/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 5m
  timeout: 15m
  dependsOn:
    - name: gatewayapi-release
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  path: "./00-core/01_cilium/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 5m
  timeout: 15m
  dependsOn:
    - name: cilium-release