apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  path: "./00-core/04_cert-manager/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 5m
  timeout: 15m
  dependsOn:
    - name: gateway-release
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  path: "./00-core/04_cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 5m
  timeout: 15m
  dependsOn:
    - name: cert-manager-release