apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - longhorn.yaml

configMapGenerator:
  - name: longhorn-values
    files:
      - longhorn/values.yaml

generatorOptions:
  disableNameSuffixHash: true