apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.18.2
  url: oci://quay.io/jetstack/charts/cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://aureq.github.io/cert-manager-webhook-ovh/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  interval: 30m
  releaseName: cert-manager
  install:
    createNamespace: true
  targetNamespace: cert-manager
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    crds:
      enabled: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cm-webhook-ovh
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager-release
  install:
    createNamespace: true
  targetNamespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh-charts
        namespace: flux-system
      version: 0.7.x
  values:
    groupName: "ovh.example"
    configVersion: "0.0.1"
    issuers:
      - name: le-prod
        create: true
        kind: ClusterIssuer
        namespace: default
        cnameStrategy: None
        acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
        email: aurel@beerus.fr
        ovhEndpointName: ovh-eu
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-credentials
            key: applicationKey
          applicationSecretRef:
            name: ovh-credentials
            key: applicationSecret
          consumerKeyRef:
            name: ovh-credentials
            key: consumerKey
