---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bazarr
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: bazarr
    namespace: flux-system
  interval: 1h
  targetNamespace: media
  values:
    controllers:
      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            ports:
            - containerPort: &port 6767
              name: http
              protocol: TCP
            image:
              repository: ghcr.io/home-operations/bazarr
              tag: 1.5.5@sha256:0949a30fb6e6703a63aaa9775760b8af820f7871f6a9aa9207e2ea00fd855e2c
            env:
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/system/ping
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 20m
              limits:
                memory: 350Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1027
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: "bazarr"
        ports:
          http:
            port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: "ReadWriteOnce"
        storageClass: longhorn
        size: 100Mi
      media:
        type: nfs
        server: 192.168.0.15
        path: /volume1/media
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - bazarr.internal.beerus.fr
        parentRefs:
          - name: cilium-internal
            namespace: network
            sectionName: https