---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 24h
  url: https://longhorn.github.io/longhorn/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  releaseName: longhorn
  targetNamespace: longhorn-system
  createNamespace: true
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: "1.9.x"
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  values:
    installCRDs: true
    defaultBackupStore:
      backupTarget: nfs://192.168.0.15:/volume1/longhorn-backups