---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: sysbackup
  namespace: longhorn-system
spec:
  task: system-backup
  cron: '*/10 * * * *'
  retain: 2
  parameters:
    volume-backup-policy: if-not-present
---
apiVersion: longhorn.io/v1beta2
kind: SystemRestore
metadata:
  name: restore-sysbackup
  namespace: longhorn-system
spec:
  systemBackup: sysbacku-df17e27d-e6d4-45bd-b44a-bf62faba4ef0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-systemrestore
  namespace: longhorn-system
spec:
  template:
    spec:
      containers:
        - name: wait
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for SystemRestore to complete..."
              until [ "$(kubectl get systemrestore restore-sysbackup -n longhorn-system -o jsonpath='{.status.state}')" = "Completed" ]; do
                echo "Still waiting..."
                sleep 5
              done
              echo "SystemRestore completed!"
      restartPolicy: Never
  backoffLimit: 3
