---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: synology
  namespace: longhorn-system
spec:
  backupTargetURL: nfs://192.168.0.15:/volume1/longhorn-backups
  pollInterval: 4m30s