---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: sysbackup
  namespace: longhorn-system
spec:
  task: system-backup
  cron: '*/10 * * * *'
  retain: 1
  parameters:
    volume-backup-policy: if-not-present
  systemBackup: sysbacku-6b773701-6c64-48c9-82b8-24775d6e3384
---
apiVersion: longhorn.io/v1beta2
kind: SystemRestore
metadata:
  name: restore-sysbackup
  namespace: longhorn-system
spec:
  systemBackup: sysbacku-6b773701-6c64-48c9-82b8-24775d6e3384
