---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: sysbackup
  namespace: longhorn-system
spec:
  task: system-backup
  cron: '*/10 * * * *'
  retain: 2
  parameters:
    volume-backup-policy: if-not-present
---
apiVersion: longhorn.io/v1beta2
kind: SystemRestore
metadata:
  name: restore-sysbackup
  namespace: longhorn-system
spec:
  systemBackup: sysbacku-9960e1cb-1ce1-48ed-adc7-01d3963d5ea5 #This value is changed automatically by automation when rebuilding the cluster. In nominal state never reapplied
# This job waits for the SystemRestore to complete
# It is to ensure that the restore process has finished before proceeding with other deployments relying on PV
# Thanks to wait: true, FluxCD will wait for Completed status on the job before proceeding
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-systemrestore
  namespace: longhorn-system
spec:
  template:
    spec:
      serviceAccountName: longhorn-service-account
      containers:
        - name: wait
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for SystemRestore to complete..."
              until [ "$(kubectl get systemrestore restore-sysbackup -n longhorn-system -o jsonpath='{.status.state}')" = "Completed" ]; do
                echo "Still waiting..."
                sleep 5
              done
              echo "SystemRestore completed!"
      restartPolicy: Never
  backoffLimit: 3
