---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: signoz
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.signoz.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: signoz
  namespace: monitoring
spec:
  releaseName: signoz
  targetNamespace: monitoring
  createNamespace: true
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 20m
  values:
    global:
      storageClass: longhorn
    clickhouse:
      installCustomStorageClass: true
    clickhouseOperator:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-k8s-infra-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: k8s-infra
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  values:
    global:
      cloud: others
      clusterName: canadium
      deploymentEnvironment: production
    otelCollectorEndpoint: signoz-release-otel-collector.monitoring.svc.cluster.local:4317
    otelInsecure: true
    presets:
      otlpExporter:
        enabled: true
      loggingExporter:
        enabled: false