---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: signoz
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.signoz.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: signoz
  namespace: flux-system
spec:
  releaseName: signoz
  targetNamespace: monitoring
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  interval: 30m
  timeout: 20m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      storageClass: longhorn
    clickhouse:
      installCustomStorageClass: true
    clickhouseOperator:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-k8s-infra-release
  namespace: flux-system
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: k8s-infra
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  interval: 30m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      cloud: others
      clusterName: canadium
      deploymentEnvironment: production
    otelCollectorEndpoint: signoz-release-otel-collector.monitoring.svc.cluster.local:4317
    otelInsecure: true
    presets:
      otlpExporter:
        enabled: true
      hostMetrics:
        enabled: true
        collectionInterval: 60s
      logsCollection:
        enabled: true
      loggingExporter:
        enabled: false
      kubeletMetrics:
        enabled: true
        collectionInterval: 60s
      kubernetesAttributes:
        enabled: true
        passthrough: true