apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
spec:
  interval: 10m
  path: "./00-core"
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
spec:
  interval: 10m
  path: "./10-platform"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: apps
  dependsOn:
    - name: core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 10m
  path: "./20-apps"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  dependsOn:
    - name: platform