---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: flux-system
spec:
  targetNamespace: media
  chartRef:
    kind: OCIRepository
    name: seerr
  interval: 1h
  values:
    controllers:
      seerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            ports:
            - containerPort: &port 5055
              name: http
              protocol: TCP
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: develop@sha256:14b676bf75442d3e57913ef276103d16d2e5c6c1ef61153a6f5133da7c6c74bd
            env:
              TZ: America/New_York
              LOG_LEVEL: "info"
              PORT: *port
              API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: seerr-secret
                    key: api_key
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 300Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1027
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - ombi.beerus.fr
          - seerr.beerus.fr
          - requests.beerus.fr
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: "ReadWriteOnce"
        storageClass: longhorn
        size: 50Mi
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir
      cache:
        type: emptyDir
        globalMounts:
         - path: /app/.next/cache