apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-release
  namespace: flux-system
spec:
  path: "./00-core/05_longhorn/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 5m
  timeout: 14m
  dependsOn:
    - name: kyverno-config
---

# Since Flux doesn't have a way to wait a bit before applying the ks, I use this dummy one
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wait-2min-longhorn
  namespace: flux-system
spec:
  interval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./00-core/05_longhorn/dummy"
  prune: false
  wait: true
  dependsOn:
    - name: longhorn-release

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  path: "./00-core/05_longhorn/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 5m
  retryInterval: 5m
  timeout: 25m
  dependsOn:
    - name: wait-2min-longhorn