---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kured
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubereboot.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured-release
  namespace: kube-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  chart:
    spec:
      chart: kured
      version: "5.x.x"
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  values:
    configuration:
      rebootSentinel: /var/run/reboot-required