apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml
  - pvc.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
    path: patch-podinfo-volume.yaml