apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml
  - pvc.yaml
patches:
  - target:
      kind: Deployment
      name: podinfo
      namespace: podinfo
    patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: longhorn-data
          persistentVolumeClaim:
            claimName: podinfo-longhorn-pvc
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: longhorn-data
          mountPath: /data2