apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age