apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo
spec:
  template:
    spec:
      volumes:
        - name: longhorn-data
          persistentVolumeClaim:
            claimName: podinfo-longhorn-pvc
      containers:
        - name: podinfo
          volumeMounts:
            - name: longhorn-data
              mountPath: /data2