apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-longhorn-pvc
  namespace: podinfo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn