apiVersion: ENC[AES256_GCM,data:zEo=,iv:G79gyPifgT09wPldLFvUgroTwEhB7KTIsl+c6D8o1k0=,tag:r6ZEVvkxYh47Z0OR4qi7+w==,type:str]
data:
    sops: ENC[AES256_GCM,data:tT5VVmdTXEs=,iv:X1Y30CjwzV7m/qIxldiGcPpFRM3aBbvHX9ukzcwzy2s=,tag:3dKGwRudwmwbJ53O5tGR/A==,type:str]
kind: ENC[AES256_GCM,data:OTJoTM9O,iv:G1fnSshF0NpghzXYYwpY26UBV5sNPM3oLEdDIylDC6w=,tag:ZuKvUcsgWeLHa44bdVOK3g==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:tFCUgFvz468=,iv:dxKz5/S6gDi0+C8GdT9vYNjt4zlr2gjbJ5noreG0ppQ=,tag:jrZgwidGbgPKgnRIpqsPEw==,type:str]
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNW1FV1FWZ052d2Ywb2dW
            NGpqOFc0TzQ2VnFNUVJTZnNodXk4UWJ5dW5zClB2NjZRM2djdHR3a2JOVjZoL1BY
            UWpQeVl3Vk1MTkJEZWxQWnh4YWdUNTgKLS0tIE51SUdiTDVVQk5SNGhJZ2lhK1Jl
            NHlnK3ZCYVN6WWJFOFROWTFheC9zM00KMJhslb08ipWlLEOg69oZkTQ8Jj7XQe/5
            XGM3X+IB9avMHWZTmJZ/d/kQhFQ5rlskeBljIZWOALgt7bGABwllFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T20:00:14Z"
    mac: ENC[AES256_GCM,data:d75t6UaAtf/NqVakapJMaWkjqcFfawYi5oi/f72b+o/hRYZ2E3o0sfR8qAADxXCysUFcmIKjc/iYRL0kwwlC+QhI7tYxqYkRcqsU5INbGC++hykWLhnUb70AJnHeGKkmp6ShGQTaTJHhQ4BucyMlYA4UqUtYGJRvCFGHrTNMsUw=,iv:Bi57mSB+3ZH32seFmZKYAiANps/6NY/EZMFqJtmx4FY=,tag:fI5abJaq7FGJx/AtE2pUYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2