apiVersion: batch/v1
kind: Job
metadata:
  name: wait-2min-job
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["sleep", "120"]
      restartPolicy: Never