apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.18.2
  url: oci://quay.io/jetstack/charts/cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  interval: 30m
  releaseName: cert-manager
  targetNamespace: kube-system
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    crds:
      enable: true
    prometheus:
      servicemonitor:
        enabled: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true